CREATE TABLE vehicles (
  id UUID PRIMARY KEY,
  plate VARCHAR(20) NOT NULL UNIQUE,
  make VARCHAR(80) NOT NULL,
  model VARCHAR(80) NOT NULL,
  year INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  fuel_type VARCHAR(20) NOT NULL,
  tank_capacity_l INTEGER NOT NULL,
  odometer_km INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);